# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,BreezeX-RosePine-Linux
env = HYPRCURSOR_THEME,rose-pine-hyprcursor
env = HYPRCURSOR_SIZE,24
env = QT_STYLE_OVERRIDE, kvantum
env = QT_QPA_PLATFORMTHEME, qt6ct
env = MPD_HOST, localhost
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
