format = """
$shell\
[░▒▓](#4b0082)\
[ ](bg:#4b0082 fg:#8f00f8)\
$username\
[](bg:#560096 fg:#4b0082)\
$directory\
[](fg:#560096 bg:#6200a9)\
$git_branch\
$git_status\
[](fg:#6200a9 bg:#6d00bd)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#6d00bd bg:#7800d0)\
$time\
[ ](fg:#7800d0)\
"""
#       indigo-6 = '#8f00f8'
# 	indigo-5 = '#8400e4'
# 	indigo-4 = '#7800d0'
# 	indigo-3 = '#6d00bd'
# 	indigo-2 = '#6200a9'
# 	indigo-1 = '#560096'
#       indigo1 = '#4b0082'
# 	indigo2 = '#34005b'
# 	indigo3 = '#290047'
# 	indigo4 = '#1e0034'
# 	indigo5 = '#120020'
# 	indigo6 = '#07000c'
[username]
show_always = true
style_user = "fg:#8400e4 bg:#4b0082"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

[directory]
style = "fg:#e3e5e5 bg:#560096"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#290047"
format = '[[ $time ](fg:#290047 bg:#7800d0)]($style)'

[shell]
fish_indicator = ' 󰈺 '
bash_indicator = '  '
zsh_indicator = ' %_ '
unknown_indicator = 'mystery shell'
style = "bg:#1e0034 fg:#8f00f8"
disabled = false
